# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-17 08:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cost', models.IntegerField(default=200)),
                ('recurring', models.BooleanField(default=False)),
                ('reg_date', models.DateField(default=datetime.date.today)),
                ('description', models.CharField(max_length=300)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('monthly_wage', models.IntegerField(default=25000)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='DevMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('role', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('description', models.CharField(max_length=1000)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='manager.Client')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('developer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='manager.Developer')),
            ],
            options={
                'ordering': ('developer',),
            },
        ),
        migrations.AddField(
            model_name='project',
            name='developers',
            field=models.ManyToManyField(through='manager.DevMembership', to='manager.Developer'),
        ),
        migrations.AddField(
            model_name='devmembership',
            name='developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Developer'),
        ),
        migrations.AddField(
            model_name='devmembership',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Project'),
        ),
        migrations.AddField(
            model_name='billable',
            name='developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billables', to='manager.Developer'),
        ),
        migrations.AddField(
            model_name='billable',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billables', to='manager.Project'),
        ),
        migrations.AddField(
            model_name='project',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='manager.Lead'),
        ),
    ]
