# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 08:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billable',
            old_name='billable_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='developer',
            old_name='developer_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_name',
            new_name='name',
        ),
    ]
