# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20170328_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='billable',
            name='cost',
            field=models.IntegerField(default=200),
        ),
    ]
