# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 11:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_billable_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billable',
            old_name='project_name',
            new_name='project',
        ),
    ]
