# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20170328_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='hours_worked',
            field=models.IntegerField(default=0),
        ),
    ]
