# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_auto_20170328_1550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billable',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='developer',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='billable',
            name='developer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='billables', to='manager.Developer'),
        ),
        migrations.AlterField(
            model_name='billable',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billables', to='manager.Project'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='developers', to='manager.Project'),
        ),
    ]
