# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 11:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_auto_20170405_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billable',
            name='developer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='billables', to=settings.AUTH_USER_MODEL),
        ),
    ]
