# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_auto_20170405_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='project',
        ),
        migrations.AddField(
            model_name='developer',
            name='projects',
            field=models.ManyToManyField(related_name='developers', to='manager.Project'),
        ),
        migrations.AlterField(
            model_name='billable',
            name='developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billables', to='manager.Developer'),
        ),
    ]
