# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 07:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_auto_20170406_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='projects',
        ),
        migrations.AddField(
            model_name='developer',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='developers', to='manager.Project'),
            preserve_default=False,
        ),
    ]
